version: 0.2

env:
  shell: bash

phases:
  build:
    commands:
      - npm ci
      - npm run build

  post_build:
    commands:
      - aws s3 mb s3://tenant-$TENANT_ID
      - aws s3 sync ./build s3://autshop-tenant-$TENANT_ID/